name: Deferable - build module
run-name: ${{ github.actor }} testing deferable
on: [push]
jobs:
    Setup:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: npm ci
            - run: npm test

